DB Versioning (GSI-1128)
ghga-de/epic-docs pull request #129
Opened 2024-11-19 17:16 UTC by TheByronHimes

2025-01-14 09:44 UTC, Cito requested changes
Thanks for working on this, made some suggestions.

2025-01-14 09:44 UTC, Cito commented on 62-california-condor/technical_specification.md
> +which can be implemented in a library like `hexkit`.
Where it says "get docs" did you mean "get collections"?

The diagram should also show what happens if there is an error because otherwise it's not evident why we need temporary collections.

2025-01-14 09:44 UTC, Cito commented on 62-california-condor/technical_specification.md
> +which can be implemented in a library like `hexkit`.
I like the idea of having a framework to handle the most frequent case of updating every document in one or more collections to a new schema version. But the framework should also provide a hook to execute more complex custom migrations, like merging two collections into one.

2025-01-14 09:44 UTC, Cito commented on 62-california-condor/technical_specification.md
> +
If a service has multiple collections, we need to keep all temporary collections until the whole migration is finished and then replace all the collections.

But even that may not be sufficient. What happens if in a multi-step-migration, the step at the end fails?

Maybe we should just somehow clone or dump the database (collections) as a backup before running the complete multi-step migration and if any step fails, restore the backup?

2025-01-14 09:44 UTC, Cito commented on 62-california-condor/technical_specification.md
> +- What to do when no matching migration exists
The abstracted logic would work like a framework, i.e. the service specific code is called by the general migration code in the framework.

2025-01-14 09:44 UTC, Cito commented on 62-california-condor/technical_specification.md
> +Tests should at least verify that the migration code applies the right changes.
Good point, to detect problems early on and not cause downtime later.

2025-01-14 09:44 UTC, Cito commented on 62-california-condor/technical_specification.md
> +can be taken offline and the collections swapped out. That's a little more complex.
Another way to reduce downtime would be using parallelization. If there are multiple tables, they could be processed in parallel. Each table could be also partitioned using the primary key and then each partition migrated in a parallel process. (E.g. using a hash of the primary key module number of partitions.)

2025-01-14 13:43 UTC, TheByronHimes commented on 62-california-condor/technical_specification.md
> +
I'm in agreement with the backup strategy, I think this is also common

2025-01-14 13:43 UTC, TheByronHimes commented on 62-california-condor/technical_specification.md
> +- What to do when no matching migration exists
Yes exactly

2025-01-14 14:21 UTC, TheByronHimes commented on 62-california-condor/technical_specification.md
> +
In the case of a failure at the end of a multi-step-migration, though, it depends on where the error is occurring. If we maintain all the data in temp collections and do the replacements all at once at the end, then errors are only a real problem if they occur somewhere during the replacement stage. We can do those inside a transaction, however, in which case we only lose some time. Then, we can either try to directly perform the collection replacement again or drop the temp tables and start the migration process anew.

2025-01-14 14:23 UTC, TheByronHimes commented on 62-california-condor/technical_specification.md
> +can be taken offline and the collections swapped out. That's a little more complex.
I totally agree on the stop/deploy approach. I'm not advocating for a complex be-everything solution here, only trying to anticipate the "what if we need to minimize downtime?" questions

2025-01-15 10:47 UTC, TheByronHimes commented on 62-california-condor/technical_specification.md
> +can be taken offline and the collections swapped out. That's a little more complex.
I've updated this section

2025-01-15 14:45 UTC, TheByronHimes commented on 62-california-condor/technical_specification.md
> +2. Create `tmp_users` and `tmp_orders` and apply the indexes from the original tables.
Updated!

2025-01-15 14:46 UTC, TheByronHimes commented on 62-california-condor/technical_specification.md
> +   3. Rename `tmp_orders` to `orders`.
D'oh, you're right. I read that doc, but apparently not closely enough. I came to the same conclusion as your second comment and think it will work just as well.

2025-01-15 15:32 UTC, Cito approved these changes
Looks good, just two minor suggestions.

2025-01-15 15:32 UTC, Cito commented on 62-california-condor/technical_specification.md
> +
Regarding prefixes, maybe `tmp_new_` instead of `tmp_` and `tmp_old_` instead of `_old` ?

2025-01-15 15:32 UTC, Cito commented on 62-california-condor/images/migration flowchart.png
There should be also an arrow (maybe dotted red) from "Run Migrations" to "Raise Error" indicating that "Run Migrations" could throw an error and that the service should not start in that case.

2025-01-15 15:49 UTC, Cito approved these changes

2025-01-15 15:50 UTC, merged