poc metadata refactoring (GDEV-1565)
ghga-de/epic-docs pull request #63
Opened 2023-01-19 12:45 UTC by KerstenBreuer

Technical specification for the next metadata epic. The crayfish epic will be adapted in a separate PR.

2023-01-20 11:54 UTC, lkuchenb requested changes
Thanks, see comments above!

2023-01-20 11:54 UTC, lkuchenb commented on 25-pacific_lamprey/technical_specification.md
> +- A implementation that can be run by data stewards locally,
```suggestion
- An implementation that can be run by data stewards locally,
```

2023-01-20 11:54 UTC, lkuchenb commented on 25-pacific_lamprey/technical_specification.md
> +- not includes:
```suggestion
- does not include:
```

2023-01-20 11:54 UTC, lkuchenb commented on 25-pacific_lamprey/technical_specification.md
> +    - REST APIs for querying the above artifacts
Does this include code that serves this API or only API design? How is this to be seen in the context of a tool that is to be "run by data stewards locally"?

2023-01-20 13:33 UTC, Cito commented on 25-pacific_lamprey/technical_specification.md
> +    - REST APIs for querying the above artifacts
As discussed, if it includes code that serves the API, then add side-loading the generated artifiacts into the database as separate point before this one.

2023-01-20 13:33 UTC, Cito submitted a review, later dismissed

2023-01-27 09:24 UTC, Cito approved these changes

2023-02-01 13:00 UTC, lkuchenb approved these changes

2023-02-01 14:42 UTC, merged